import { CategoryType, ProductType } from "@/types";

export const MOCK_CATEGORIES: CategoryType[] = [
  {
    id: "cat-ground",
    name: "Pure Ground Powders",
    slug: "ground-spices",
    description: "Pure Red Chilli, Turmeric, and Coriander powders stone-ground at low temperatures with zero adulteration.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
  {
    id: "cat-whole",
    name: "Whole Spices & Seeds",
    slug: "whole-spices",
    description: "Sun-dried Coriander seeds, Tellicherry Black Pepper, and Extra Bold Green Cardamom bursting with natural aroma.",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
  {
    id: "cat-blends",
    name: "Authentic Masala Blends",
    slug: "heritage-blends",
    description: "Traditional slow-roasted spice blends crafted for rich royal curries, biryanis, and sabzis.",
    image: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
  {
    id: "cat-exotic",
    name: "Royal Kashmiri Saffron",
    slug: "exotics-and-saffron",
    description: "Grade A1 ISO-certified Kashmiri Mongra Saffron with deep crimson stigmas and unmatched fragrance.",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
];

export const MOCK_PRODUCTS: ProductType[] = [
  {
    id: "prod-red-chilli",
    name: "Pure Red Chilli Powder (Lal Mirch Powder)",
    slug: "pure-red-chilli-powder",
    scientificName: "Capsicum annuum",
    origin: "Nagaur, Rajasthan",
    description: "Finely ground from selected stemless sun-dried red chillies of Rajasthan. Delivers an authentic vibrant red color and natural fiery warmth without any artificial color enhancers or fillers. Ideal for everyday Indian curries, marinades, and gravies.",
    shortDesc: "100% pure sun-dried stemless red chillies delivering authentic heat and natural color.",
    spiceLevel: "HOT",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Winter 2024 Fresh Harvest",
    aromaProfile: "Fiery, Pungent, Earthy, Smoky",
    categoryId: "cat-ground",
    rating: 4.9,
    reviewCount: 186,
    images: [
      {
        id: "img-chilli-1",
        url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
        alt: "Pure Red Chilli Powder",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-chilli-100g",
        productId: "prod-red-chilli",
        weight: "100g Pack",
        weightGrams: 100,
        price: 35,
        mrp: 45,
        stock: 120,
        sku: "ND-RC-100G",
      },
      {
        id: "var-chilli-250g",
        productId: "prod-red-chilli",
        weight: "250g Pack",
        weightGrams: 250,
        price: 75,
        mrp: 95,
        stock: 85,
        sku: "ND-RC-250G",
      },
      {
        id: "var-chilli-500g",
        productId: "prod-red-chilli",
        weight: "500g Pack",
        weightGrams: 500,
        price: 140,
        mrp: 175,
        stock: 60,
        sku: "ND-RC-500G",
      },
      {
        id: "var-chilli-1kg",
        productId: "prod-red-chilli",
        weight: "1kg Bulk Pack",
        weightGrams: 1000,
        price: 240,
        mrp: 290,
        stock: 45,
        sku: "ND-RC-1KG",
      },
    ],
  },
  {
    id: "prod-coriander-powder",
    name: "Pure Coriander Powder (Dhaniya Powder)",
    slug: "pure-coriander-powder",
    scientificName: "Coriandrum sativum",
    origin: "Nagaur, Rajasthan",
    description: "Stone-ground from high-grade green coriander seeds of Rajasthan. Carefully cleaned and milled at gentle low temperatures to preserve natural volatile essential oils, offering a soothing sweet-citrusy aroma and rich curry base.",
    shortDesc: "Stone-ground pure coriander seeds retaining natural volatile aroma and sweetness.",
    spiceLevel: "MILD",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Spring 2024",
    aromaProfile: "Sweet, Citrus, Floral, Warm Earthy",
    categoryId: "cat-ground",
    rating: 4.8,
    reviewCount: 142,
    images: [
      {
        id: "img-dhaniya-1",
        url: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80",
        alt: "Pure Coriander Powder",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-dhaniya-100g",
        productId: "prod-coriander-powder",
        weight: "100g Pack",
        weightGrams: 100,
        price: 30,
        mrp: 40,
        stock: 150,
        sku: "ND-CP-100G",
      },
      {
        id: "var-dhaniya-250g",
        productId: "prod-coriander-powder",
        weight: "250g Pack",
        weightGrams: 250,
        price: 65,
        mrp: 85,
        stock: 90,
        sku: "ND-CP-250G",
      },
      {
        id: "var-dhaniya-500g",
        productId: "prod-coriander-powder",
        weight: "500g Pack",
        weightGrams: 500,
        price: 120,
        mrp: 150,
        stock: 70,
        sku: "ND-CP-500G",
      },
      {
        id: "var-dhaniya-1kg",
        productId: "prod-coriander-powder",
        weight: "1kg Bulk Pack",
        weightGrams: 1000,
        price: 200,
        mrp: 250,
        stock: 50,
        sku: "ND-CP-1KG",
      },
    ],
  },
  {
    id: "prod-turmeric-powder",
    name: "Pure Turmeric Powder (High Curcumin Haldi)",
    slug: "pure-turmeric-powder",
    scientificName: "Curcuma longa",
    origin: "Nagaur, Rajasthan",
    description: "Finely milled pure golden turmeric rhizomes containing high natural curcumin levels. Sourced directly from authentic harvest lots, with absolutely zero lead chromate, chalk, or chemical coloring.",
    shortDesc: "Rich golden turmeric with high natural curcumin and zero artificial colorants.",
    spiceLevel: "NONE",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Winter 2024",
    aromaProfile: "Warm, Woody, Peppery, Golden Earthy",
    categoryId: "cat-ground",
    rating: 4.9,
    reviewCount: 168,
    images: [
      {
        id: "img-turmeric-1",
        url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
        alt: "Pure Turmeric Powder",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-haldi-100g",
        productId: "prod-turmeric-powder",
        weight: "100g Pack",
        weightGrams: 100,
        price: 35,
        mrp: 45,
        stock: 130,
        sku: "ND-TP-100G",
      },
      {
        id: "var-haldi-250g",
        productId: "prod-turmeric-powder",
        weight: "250g Pack",
        weightGrams: 250,
        price: 80,
        mrp: 100,
        stock: 95,
        sku: "ND-TP-250G",
      },
      {
        id: "var-haldi-500g",
        productId: "prod-turmeric-powder",
        weight: "500g Pack",
        weightGrams: 500,
        price: 150,
        mrp: 190,
        stock: 65,
        sku: "ND-TP-500G",
      },
      {
        id: "var-haldi-1kg",
        productId: "prod-turmeric-powder",
        weight: "1kg Bulk Pack",
        weightGrams: 1000,
        price: 260,
        mrp: 320,
        stock: 40,
        sku: "ND-TP-1KG",
      },
    ],
  },
  {
    id: "prod-coriander-seeds",
    name: "Whole Coriander Seeds (Sabut Dhaniya)",
    slug: "whole-coriander-seeds",
    scientificName: "Coriandrum sativum",
    origin: "Nagaur, Rajasthan",
    description: "Sun-cured, machine cleaned, premium bold green coriander seeds with high volatile oil concentration. Perfect for roasting, coarse crushing, or tempering for authentic traditional curries and pickles.",
    shortDesc: "Machine-cleaned whole coriander seeds with intense fragrant essential oils.",
    spiceLevel: "NONE",
    organic: true,
    featured: true,
    bestseller: false,
    harvestSeason: "Spring 2024",
    aromaProfile: "Citrusy, Herbal, Warm Woody",
    categoryId: "cat-whole",
    rating: 4.8,
    reviewCount: 94,
    images: [
      {
        id: "img-dhaniya-seeds-1",
        url: "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80",
        alt: "Whole Coriander Seeds",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-seeds-100g",
        productId: "prod-coriander-seeds",
        weight: "100g Pack",
        weightGrams: 100,
        price: 35,
        mrp: 45,
        stock: 100,
        sku: "ND-CS-100G",
      },
      {
        id: "var-seeds-250g",
        productId: "prod-coriander-seeds",
        weight: "250g Pack",
        weightGrams: 250,
        price: 75,
        mrp: 95,
        stock: 70,
        sku: "ND-CS-250G",
      },
      {
        id: "var-seeds-500g",
        productId: "prod-coriander-seeds",
        weight: "500g Pack",
        weightGrams: 500,
        price: 140,
        mrp: 175,
        stock: 50,
        sku: "ND-CS-500G",
      },
      {
        id: "var-seeds-1kg",
        productId: "prod-coriander-seeds",
        weight: "1kg Bulk Pack",
        weightGrams: 1000,
        price: 240,
        mrp: 290,
        stock: 35,
        sku: "ND-CS-1KG",
      },
    ],
  },
  {
    id: "prod-cardamom",
    name: "Alleppey Green Cardamom (8mm+ Extra Bold)",
    slug: "alleppey-green-cardamom-jumbo",
    scientificName: "Elettaria cardamomum",
    origin: "Idukki Estate, Kerala",
    description: "Extra Bold 8mm+ green cardamom pods brimming with aromatic resinous black seeds. Preserved with natural essential oils for intense fragrance in sweets, biryanis, and chai.",
    shortDesc: "Extra bold 8mm+ pods bursting with fragrant cineole and essential oils.",
    spiceLevel: "NONE",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Winter 2024",
    aromaProfile: "Sweet, Eucalyptus, Floral, Citrusy",
    categoryId: "cat-whole",
    rating: 4.9,
    reviewCount: 154,
    images: [
      {
        id: "img-cardamom-1",
        url: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=800&q=80",
        alt: "Alleppey Green Cardamom",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-cardamom-100g",
        productId: "prod-cardamom",
        weight: "100g Glass Jar",
        weightGrams: 100,
        price: 349,
        mrp: 420,
        stock: 60,
        sku: "ND-CRD-100G",
      },
      {
        id: "var-cardamom-250g",
        productId: "prod-cardamom",
        weight: "250g Pack",
        weightGrams: 250,
        price: 799,
        mrp: 999,
        stock: 40,
        sku: "ND-CRD-250G",
      },
      {
        id: "var-cardamom-500g",
        productId: "prod-cardamom",
        weight: "500g Pack",
        weightGrams: 500,
        price: 1499,
        mrp: 1899,
        stock: 25,
        sku: "ND-CRD-500G",
      },
    ],
  },
  {
    id: "prod-black-pepper",
    name: "Tellicherry Black Pepper (Garbled Extra Bold)",
    slug: "tellicherry-black-pepper-tgseb",
    scientificName: "Piper nigrum",
    origin: "Wayanad, Kerala",
    description: "Sun-cured Tellicherry extra bold whole black peppercorns (TGSEB) with high piperine content. Provides sharp aromatic heat with complex citrus and pine undertones.",
    shortDesc: "King of Spices. Extra bold peppercorns with bold heat and natural piperine.",
    spiceLevel: "MEDIUM",
    organic: true,
    featured: true,
    bestseller: false,
    harvestSeason: "Winter 2024",
    aromaProfile: "Sharp, Pungent, Woody, Citrus Resin",
    categoryId: "cat-whole",
    rating: 4.8,
    reviewCount: 118,
    images: [
      {
        id: "img-pepper-1",
        url: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80",
        alt: "Tellicherry Black Pepper",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-pepper-100g",
        productId: "prod-black-pepper",
        weight: "100g Pack",
        weightGrams: 100,
        price: 120,
        mrp: 150,
        stock: 80,
        sku: "ND-BP-100G",
      },
      {
        id: "var-pepper-250g",
        productId: "prod-black-pepper",
        weight: "250g Pack",
        weightGrams: 250,
        price: 280,
        mrp: 350,
        stock: 50,
        sku: "ND-BP-250G",
      },
      {
        id: "var-pepper-500g",
        productId: "prod-black-pepper",
        weight: "500g Pack",
        weightGrams: 500,
        price: 520,
        mrp: 650,
        stock: 35,
        sku: "ND-BP-500G",
      },
      {
        id: "var-pepper-1kg",
        productId: "prod-black-pepper",
        weight: "1kg Bulk Pack",
        weightGrams: 1000,
        price: 950,
        mrp: 1200,
        stock: 25,
        sku: "ND-BP-1KG",
      },
    ],
  },
  {
    id: "prod-saffron",
    name: "Royal Kashmiri Mongra Saffron (Grade A1)",
    slug: "royal-kashmiri-mongra-saffron",
    scientificName: "Crocus sativus",
    origin: "Pampore, Kashmir",
    description: "100% pure all-red Mongra saffron filaments handpicked from high-altitude fields of Pampore. Lab-certified for peak crocin color potency and natural safranal aroma.",
    shortDesc: "Pristine Grade A1 all-red Mongra saffron with peak color and aroma potency.",
    spiceLevel: "NONE",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Autumn 2024",
    aromaProfile: "Floral, Honey, Earthy, Sweet Hay",
    categoryId: "cat-exotic",
    rating: 5.0,
    reviewCount: 89,
    images: [
      {
        id: "img-saffron-1",
        url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
        alt: "Kashmiri Mongra Saffron",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-saffron-1g",
        productId: "prod-saffron",
        weight: "1g Sealed Box",
        weightGrams: 1,
        price: 420,
        mrp: 550,
        stock: 100,
        sku: "ND-SAF-1G",
      },
      {
        id: "var-saffron-2g",
        productId: "prod-saffron",
        weight: "2g Sealed Box",
        weightGrams: 2,
        price: 799,
        mrp: 1050,
        stock: 60,
        sku: "ND-SAF-2G",
      },
      {
        id: "var-saffron-5g",
        productId: "prod-saffron",
        weight: "5g Luxury Box",
        weightGrams: 5,
        price: 1899,
        mrp: 2499,
        stock: 30,
        sku: "ND-SAF-5G",
      },
    ],
  },
  {
    id: "prod-garam-masala",
    name: "Royal Heritage Garam Masala (18-Spice Blend)",
    slug: "royal-heritage-garam-masala",
    scientificName: "Artisanal Spice Blend",
    origin: "Nagaur, Rajasthan",
    description: "An authentic 18-spice slow-roasted artisanal garam masala. Balanced with stone-ground coriander, cardamom, cloves, cinnamon, mace, and cumin for gourmet curries and royal gravies.",
    shortDesc: "Authentic 18-spice slow-roasted blend for exquisite curries and gravies.",
    spiceLevel: "MEDIUM",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Fresh Batch",
    aromaProfile: "Warm, Sweet Pungent, Rich Cinnamon, Clove",
    categoryId: "cat-blends",
    rating: 4.9,
    reviewCount: 132,
    images: [
      {
        id: "img-garam-1",
        url: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=800&q=80",
        alt: "Royal Garam Masala Blend",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-garam-100g",
        productId: "prod-garam-masala",
        weight: "100g Pack",
        weightGrams: 100,
        price: 60,
        mrp: 75,
        stock: 90,
        sku: "ND-GM-100G",
      },
      {
        id: "var-garam-250g",
        productId: "prod-garam-masala",
        weight: "250g Pack",
        weightGrams: 250,
        price: 140,
        mrp: 175,
        stock: 65,
        sku: "ND-GM-250G",
      },
      {
        id: "var-garam-500g",
        productId: "prod-garam-masala",
        weight: "500g Pack",
        weightGrams: 500,
        price: 260,
        mrp: 320,
        stock: 45,
        sku: "ND-GM-500G",
      },
      {
        id: "var-garam-1kg",
        productId: "prod-garam-masala",
        weight: "1kg Bulk Pack",
        weightGrams: 1000,
        price: 490,
        mrp: 600,
        stock: 30,
        sku: "ND-GM-1KG",
      },
    ],
  },
];
