import { CategoryType, ProductType } from "@/types";

export const MOCK_CATEGORIES: CategoryType[] = [
  {
    id: "cat-whole",
    name: "Whole Spices",
    slug: "whole-spices",
    description: "Sun-dried, unadulterated whole pods, seeds, and barks brimming with essential oils.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
  {
    id: "cat-ground",
    name: "Stone-Ground Powders",
    slug: "ground-spices",
    description: "Cold stone-ground at low RPM to preserve volatile aromatic terpenes and rich pigments.",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
  {
    id: "cat-exotic",
    name: "Exotics & Saffron",
    slug: "exotics-and-saffron",
    description: "Pristine Mongra saffron, high-elevation mace blades, and rare artisanal botanicals.",
    image: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
  {
    id: "cat-blends",
    name: "Heritage Masalas",
    slug: "heritage-blends",
    description: "Secret family spice blends roasted to perfection for royal curries, biryanis, and chai.",
    image: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=600&q=80",
    featured: true,
  },
];

export const MOCK_PRODUCTS: ProductType[] = [
  {
    id: "prod-cardamom",
    name: "Alleppey Green Cardamom (8mm+ Jumbo Pods)",
    slug: "alleppey-green-cardamom-jumbo",
    scientificName: "Elettaria cardamomum",
    origin: "Idukki Hills, Kerala",
    description: "Handpicked from mist-covered plantations at 3,500ft elevation. These lush green pods are graded at 8mm+ diameter, packed with dark resinous seeds overflowing with intense cineole and sweet herbal aroma.",
    shortDesc: "Jumbo 8mm+ pods bursting with fragrant sweetness and high essential oil content.",
    spiceLevel: "NONE",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Winter 2024",
    aromaProfile: "Sweet, Eucalyptus, Floral, Citrusy",
    categoryId: "cat-whole",
    rating: 4.9,
    reviewCount: 142,
    images: [
      {
        id: "img-cardamom-1",
        url: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=800&q=80",
        alt: "Alleppey Green Cardamom Pods",
        isPrimary: true,
        order: 1,
      },
      {
        id: "img-cardamom-2",
        url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
        alt: "Cardamom Harvest Kerala",
        isPrimary: false,
        order: 2,
      },
    ],
    variants: [
      {
        id: "var-cardamom-100g",
        productId: "prod-cardamom",
        weight: "100g Glass Jar",
        weightGrams: 100,
        price: 349,
        mrp: 420,
        stock: 50,
        sku: "ND-CRD-100G",
      },
      {
        id: "var-cardamom-250g",
        productId: "prod-cardamom",
        weight: "250g Aroma Pouch",
        weightGrams: 250,
        price: 799,
        mrp: 999,
        stock: 35,
        sku: "ND-CRD-250G",
      },
      {
        id: "var-cardamom-500g",
        productId: "prod-cardamom",
        weight: "500g Value Pack",
        weightGrams: 500,
        price: 1499,
        mrp: 1899,
        stock: 20,
        sku: "ND-CRD-500G",
      },
    ],
  },
  {
    id: "prod-saffron",
    name: "Kashmiri Mongra Saffron (Grade A1)",
    slug: "kashmiri-mongra-saffron-grade-a1",
    scientificName: "Crocus sativus",
    origin: "Pampore, Kashmir",
    description: "The gold standard of saffron worldwide. 100% pure deep crimson red stigmas harvested from the plateau of Pampore. Unbroken threads rich in safranal and crocin for radiant golden coloring and ethereal floral aroma.",
    shortDesc: "Pure crimson Mongra threads with unmatched crocin coloring power and floral aroma.",
    spiceLevel: "NONE",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Autumn 2024",
    aromaProfile: "Warm Honey, Metallic Sweetness, Hay-like Floral",
    categoryId: "cat-exotic",
    rating: 5.0,
    reviewCount: 98,
    images: [
      {
        id: "img-saffron-1",
        url: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80",
        alt: "Kashmiri Saffron Threads in Jar",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-saffron-1g",
        productId: "prod-saffron",
        weight: "1g Royal Acrylic Box",
        weightGrams: 1,
        price: 499,
        mrp: 650,
        stock: 120,
        sku: "ND-SAF-1G",
      },
      {
        id: "var-saffron-2g",
        productId: "prod-saffron",
        weight: "2g Collectors Tin",
        weightGrams: 2,
        price: 949,
        mrp: 1250,
        stock: 60,
        sku: "ND-SAF-2G",
      },
      {
        id: "var-saffron-5g",
        productId: "prod-saffron",
        weight: "5g Heritage Vault",
        weightGrams: 5,
        price: 2199,
        mrp: 2900,
        stock: 25,
        sku: "ND-SAF-5G",
      },
    ],
  },
  {
    id: "prod-pepper",
    name: "Tellicherry Garbled Extra Bold Pepper (TGSEB)",
    slug: "tellicherry-black-pepper-tgseb",
    scientificName: "Piper nigrum",
    origin: "Thalassery, Malabar Coast",
    description: "The crown jewel of peppercorns. Only the top 10% largest, fully ripened berries (4.75mm+) are classified as TGSEB. Delivers robust heat paired with nuanced citrus and woody notes.",
    shortDesc: "King of Spices. Extra large 4.75mm+ sun-cured peppercorns with complex piperine heat.",
    spiceLevel: "HOT",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Spring 2024",
    aromaProfile: "Pungent, Cedarwood, Warm Pine, Citrus",
    categoryId: "cat-whole",
    rating: 4.9,
    reviewCount: 110,
    images: [
      {
        id: "img-pepper-1",
        url: "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80",
        alt: "Tellicherry Black Pepper TGSEB",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-pepper-100g",
        productId: "prod-pepper",
        weight: "100g Glass Jar with Grinder Cap",
        weightGrams: 100,
        price: 199,
        mrp: 250,
        stock: 80,
        sku: "ND-PEP-100G",
      },
      {
        id: "var-pepper-250g",
        productId: "prod-pepper",
        weight: "250g Refill Pouch",
        weightGrams: 250,
        price: 449,
        mrp: 550,
        stock: 65,
        sku: "ND-PEP-250G",
      },
      {
        id: "var-pepper-500g",
        productId: "prod-pepper",
        weight: "500g Value Pack",
        weightGrams: 500,
        price: 849,
        mrp: 1050,
        stock: 40,
        sku: "ND-PEP-500G",
      },
    ],
  },
  {
    id: "prod-cinnamon",
    name: "True Ceylon Cinnamon Quills (Alba Grade)",
    slug: "true-ceylon-cinnamon-alba",
    scientificName: "Cinnamomum verum",
    origin: "Wayanad Biosphere, Kerala",
    description: "Fragile, delicate paper-thin layers rolled into quills. Ultra-low in coumarin, offering a refined, naturally sweet woody spice that is lightyears ahead of harsh grocery-store cassia bark.",
    shortDesc: "Delicate multi-layered quills. 100% true cinnamon with ultra-low coumarin.",
    spiceLevel: "MILD",
    organic: true,
    featured: true,
    bestseller: false,
    harvestSeason: "Monsoon 2024",
    aromaProfile: "Sweet Woody, Clove-like, Warm Floral",
    categoryId: "cat-whole",
    rating: 4.8,
    reviewCount: 76,
    images: [
      {
        id: "img-cinnamon-1",
        url: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80",
        alt: "Ceylon Cinnamon Quills",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-cin-100g",
        productId: "prod-cinnamon",
        weight: "100g Pouch",
        weightGrams: 100,
        price: 249,
        mrp: 320,
        stock: 45,
        sku: "ND-CIN-100G",
      },
      {
        id: "var-cin-250g",
        productId: "prod-cinnamon",
        weight: "250g Kitchen Pack",
        weightGrams: 250,
        price: 549,
        mrp: 699,
        stock: 30,
        sku: "ND-CIN-250G",
      },
    ],
  },
  {
    id: "prod-turmeric",
    name: "Lakadong Turmeric Powder (7.5%+ Curcumin)",
    slug: "lakadong-turmeric-powder-high-curcumin",
    scientificName: "Curcuma longa",
    origin: "Jaintia Hills, Meghalaya",
    description: "Sourced directly from indigenous tribal farmers in Lakadong. Boasting an astounding 7.5% to 8.5% natural curcumin content (compared to 2% in regular turmeric). Golden amber hue with immense therapeutic potency.",
    shortDesc: "High potency turmeric with 7.5%+ curcumin stone-ground at cryogenic temperatures.",
    spiceLevel: "NONE",
    organic: true,
    featured: true,
    bestseller: true,
    harvestSeason: "Spring 2024",
    aromaProfile: "Earthy, Warm Ginger-Pungent, Deep Musky",
    categoryId: "cat-ground",
    rating: 4.9,
    reviewCount: 215,
    images: [
      {
        id: "img-turmeric-1",
        url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80",
        alt: "Lakadong Turmeric Powder",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-tur-100g",
        productId: "prod-turmeric",
        weight: "100g Tin",
        weightGrams: 100,
        price: 189,
        mrp: 230,
        stock: 95,
        sku: "ND-TUR-100G",
      },
      {
        id: "var-tur-250g",
        productId: "prod-turmeric",
        weight: "250g Pack",
        weightGrams: 250,
        price: 399,
        mrp: 499,
        stock: 70,
        sku: "ND-TUR-250G",
      },
      {
        id: "var-tur-500g",
        productId: "prod-turmeric",
        weight: "500g Value Pack",
        weightGrams: 500,
        price: 749,
        mrp: 950,
        stock: 40,
        sku: "ND-TUR-500G",
      },
    ],
  },
  {
    id: "prod-chili",
    name: "Guntur Sannam Stemless Red Chili Powder",
    slug: "guntur-sannam-red-chili-powder",
    scientificName: "Capsicum annuum",
    origin: "Guntur, Andhra Pradesh",
    description: "Sun-cured stemless S4 chilies cold pounded to retain natural capsaicin oils and vibrant natural scarlet hue. Bold fiery heat with smoky undercurrents.",
    shortDesc: "Pure Guntur S4 sun-dried chilies with striking red color and authentic piquant punch.",
    spiceLevel: "EXTRA_HOT",
    organic: true,
    featured: false,
    bestseller: false,
    harvestSeason: "Summer 2024",
    aromaProfile: "Smoky, Pungent, Fruit-peel, Fiery",
    categoryId: "cat-ground",
    rating: 4.7,
    reviewCount: 89,
    images: [
      {
        id: "img-chili-1",
        url: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80",
        alt: "Guntur Red Chili Powder",
        isPrimary: true,
        order: 1,
      },
    ],
    variants: [
      {
        id: "var-chi-250g",
        productId: "prod-chili",
        weight: "250g Pouch",
        weightGrams: 250,
        price: 220,
        mrp: 275,
        stock: 60,
        sku: "ND-CHI-250G",
      },
      {
        id: "var-chi-500g",
        productId: "prod-chili",
        weight: "500g Pack",
        weightGrams: 500,
        price: 410,
        mrp: 520,
        stock: 45,
        sku: "ND-CHI-500G",
      },
    ],
  },
];
